# ██╗ ███████╗ ██████╗   █████╗  ██╗    ██╗ ███╗   ██╗ ███████╗ ██████╗  ███████╗
# ╚═╝ ██╔════╝ ██╔══██╗ ██╔══██╗ ██║    ██║ ████╗  ██║ ██╔════╝ ██╔══██╗ ██╔════╝
# ██║ ███████╗ ██████╔╝ ███████║ ██║ █╗ ██║ ██╔██╗ ██║ █████╗   ██████╔╝ ███████╗
# ██║ ╚════██║ ██╔═══╝  ██╔══██║ ██║███╗██║ ██║╚██╗██║ ██╔══╝   ██╔══██╗ ╚════██║
# ██║ ███████║ ██║      ██║  ██║ ╚███╔███╔╝ ██║ ╚████║ ███████╗ ██║  ██║ ███████║
# ╚═╝ ╚══════╝ ╚═╝      ╚═╝  ╚═╝  ╚══╝╚══╝  ╚═╝  ╚═══╝ ╚══════╝ ╚═╝  ╚═╝ ╚══════╝
# https://www.spigotmc.org/resources/ispawners.113631/
config-version: '1.0' # <-- Don't touch this

# the delay between spawner item generation
refresh_time: 80

# the maximum number of items the spawner will generate before waiting to be sold
max_items: 10000

# the amount the max items will be multiplied by for each added spawner
max-items-multiplier: 1.5

# limits how many spawners can be stacked
max-stacked-spawners: 500

spawners:
  CREEPER:
    exp: 2
    loot:
      - GUNPOWDER
  SKELETON:
    exp: 2
    loot:
      - BONE
      - ARROW
  ZOMBIE:
    exp: 2
    loot:
      - ROTTEN_FLESH
  BLAZE:
    exp: 2
    loot:
      - BLAZE_ROD
  SPIDER:
    exp: 2
    loot:
      - STRING
      - SPIDER_EYE
  PIG:
    exp: 2
    loot:
      - PORKCHOP
  COW:
    exp: 2
    loot:
      - LEATHER
      - BEEF
  IRON_GOLEM:
    exp: 2
    loot:
      - POPPY
      - IRON_INGOT

prices:
  GUNPOWDER: 10
  BONE: 10
  ARROW: 10
  ROTTEN_FLESH: 10
  BLAZE_ROD: 10
  STRING: 10
  SPIDER_EYE: 10
  PORKCHOP: 10
  LEATHER: 10
  BEEF: 10
  POPPY: 10
  IRON_INGOT: 10
